# Generated by Django 4.2.11 on 2024-03-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='Date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
