# Generated by Django 4.2.11 on 2024-03-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.IntegerField(blank=True, null=True)),
                ('ContryName', models.CharField(blank=True, max_length=255, null=True)),
                ('CountryCode', models.CharField(blank=True, max_length=255, null=True)),
                ('TotalCount', models.IntegerField(blank=True, null=True)),
                ('Gold', models.IntegerField(blank=True, null=True)),
                ('Silver', models.IntegerField(blank=True, null=True)),
                ('Bronze', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
