# Generated by Django 4.2.11 on 2024-03-24 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medal',
            old_name='ContryName',
            new_name='CountryName',
        ),
    ]
