# Generated by Django 4.2.11 on 2024-03-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medal', '0002_rename_contryname_medal_countryname'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medal',
            table='metal',
        ),
    ]
