# Generated by Django 4.2.11 on 2024-03-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryName', models.CharField(blank=True, max_length=255, null=True)),
                ('FirstName', models.CharField(blank=True, max_length=255, null=True)),
                ('LastName', models.CharField(blank=True, max_length=255, null=True)),
                ('DBO', models.CharField(blank=True, max_length=255, null=True)),
                ('Gender', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'athlete',
            },
        ),
    ]
