# Generated by Django 4.2.11 on 2024-03-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='CountryCode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
