# Generated by Django 4.2.11 on 2024-03-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0002_athlete_countrycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='ResultId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
